### ISSUE TITLE
Route-Record cases unknown AVP error

### ISSUE THREAD

**Issue by arshadansari27** [carlosedp/diameter-dcca#1]
Hello there,

I put an erlang based relay (DRA) between the client and server you have provided, which adds route-record avp to the request and server is unable to process this avp and returns unknown avp error as shown below:

AVP: Failed-AVP(279) l=28 f=-M-
    AVP: Route-Record(282) l=20 f=-M- val=a.client.com

Any pointers on how to fix it?

**Comment by arshadansari27** [comment]
Sorry, I'm new to this, so didn't know much about dictionary. I added it to the _Gy.dia and generated the hrl and erls. Now it is working fine.

**Comment by carlosedp** [comment]
Nice, I would point this that you needed to add the dictionaries so the relay knows about the AVPs sent and received. Is the relay open source? Would you mind sharing it?

**Comment by arshadansari27** [comment]
The relay is in the otp/diameter/examples which I'm using by tweaking the pick_peer function to choose from multiple server nodes for load balancing. It is available here: https://github.com/arshadansari27/erlang-diameter-eval inside eproxy folder

have you benchmarked this server? and what should be done to make this server capable of handling around 80K requests per second? and specific vm args? here is my email arshadansari27@gmail.com so we dont clutter this issue comment with out of topic discussion :) or you can reply here.
