### ISSUE TITLE
Error: no_service

### ISSUE THREAD

**Issue by sachithmuhandiram** [carlosedp/diameter-dcca#2]
I have tried to execute the given example. I got above error when I call `client:test()`. 
`client,server,client_cb and server_cb` compiled without errors.

 Environment : Ubuntu 18.04

**Comment by carlosedp** [comment]
I would point you out to check the other repository (https://github.com/carlosedp/dcca-server-OTP). It contains a more updated version of this code written in OTP. I discontinued this version when I migrated the code to that one.

**Comment by sachithmuhandiram** [comment]
Ola Carlos

Thanks for the quick reply and I have checked new repository and it works.
I am trying to implement diameter Gx, do you have `rfc4006_cc_Gx.dia` file or at least a place to get it?

Thanks again.
Sachith

**Comment by carlosedp** [comment]
Actually, the `dcca-server-OTP/apps/dccaserver/dia/rfc4006_cc_Gy.dia` file on that repository I customized myself from other dictionaries. I believe I based mine on https://github.com/erlang/otp/blob/master/lib/diameter/examples/dict/rfc4006_cc.dia.

You might need to customize based on the AVPs you plan to use between the peers.

**Comment by sachithmuhandiram** [comment]
Thanks a lot. I will go through this.

**Comment by sachithmuhandiram** [comment]
Ola carlose.

I got a problem with defining custom avps. Specially grouped ones.
As an example 
`CC-Money ::= < AVP Header: 413 >
           { Unit-Value }
           [ Currency-Code ]`

And Currency-Code defined in differently in
`Cost-Information ::= < AVP Header: 423 >
           { Unit-Value }
           { Currency-Code }
           [ Cost-Unit ]`

Why does `Currency-Code` has two definitions with `[ ]` and `{ }`

**Comment by carlosedp** [comment]
Because CC-Money AVP contains an array of multiple Currency-Codes and Cost-Information AVP contains only one Currency-Code. {} means one and [] means an array of multiple.

**Comment by sachithmuhandiram** [comment]
Thanks a lot Carlose. I got an another one, hope this would be the last question.

some arrays are defined `*[ Value ] ` , what does this mean?

**Comment by carlosedp** [comment]
I don't remember exactly but I think that it means the field is optional (could be 0 or 1+ of this AVP). I'm not sure.

Check the documentation to confirm this:
http://erlang.org/doc/man/diameter_dict.html
https://tools.ietf.org/html/rfc6733

**Comment by sachithmuhandiram** [comment]
Thanks a lot Carlose.
